sky:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHMn23hvgsUCkp15bfM
    access-key-secret: CgzHnVwHsb47qacd7xeVqdyEVFPAgJ
    bucket-name: ztc-sky-take-out
